### ISSUE TITLE
Editing data resource licenses is broken in the new version

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/collectory-plugin#105] opened 2017-09-19 23:26 UTC
Editing data resource license information sets the "License type" to "Choose license" each time you edit the Citation/Rights/License/Permissions information. It ignores the value that was specified previously, although it does save the license if you explicitly select the license each time.

This is an urgent data loss issue, as we are in the process of auditing the licenses and citations and rights and are regularly using this functionality and do not want the license mysteriously disappearing.

CC @djtfmartin @charvolant @M-Nicholls

**Comment by djtfmartin** [comment] 2017-09-20 09:55
i know the cause. Its a mismatch between the existing licences in use and the license table we now have. I'll fix it.

**Comment by djtfmartin** [comment] 2017-09-20 20:52
This is now fixed and deployed in production

https://github.com/AtlasOfLivingAustralia/collectory-plugin/commit/d615f152af2e7f1b892ad2e724d4d625672210ee

**Closed by djtfmartin** 2017-09-20 20:52 UTC
